# Version is obsolete
# version: '3.8'  # Specifies the version of Docker Compose format being used


services:
  web: # Name of the service
    build: ./project  # Builds the image from the Dockerfile located in the 'project' directory
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000  
    # Command to run the FastAPI application using Uvicorn
    # --reload enables hot reloading during development
    # --workers 1 sets the number of Uvicorn workers to 1 (you can increase this in production for better performance)
    # --host 0.0.0.0 binds the app to all network interfaces inside the container
    # --port 8000 specifies the internal port Uvicorn will listen on

    volumes:
      - ./project:/usr/src/app  # Mounts the local 'project' directory to '/usr/src/app' inside the container for live code updates

    ports:
      - 8004:8000  # Maps port 8000 in the container to port 8004 on the host machine

    environment:
      - ENVIRONMENT=dev  # Sets the ENVIRONMENT variable to 'dev' inside the container
      - TESTING=0        # Sets the TESTING variable to '0', which could be used to toggle test mode in your app
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev        
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test

  web-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
